# Generated by Django 6.0.3 on 2026-03-21 16:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('autho', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('is_obsolete', models.BooleanField(default=False, help_text='Soft delete flag. True means the record is obsolete and should not be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('approval_status_meta', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('from_department', models.CharField(max_length=100)),
                ('to_department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('background', models.TextField()),
                ('memo_type', models.CharField(choices=[('GENERAL', 'General'), ('FINANCE', 'Finance'), ('HR', 'Human Resources'), ('IT', 'Information Technology'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('approval_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='txns', to='approvals.approvalchain')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_memos', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memos', to='autho.merchant')),
            ],
            options={
                'verbose_name': 'Memo',
                'verbose_name_plural': 'Memos',
            },
        ),
    ]
