# Generated by Django 6.0.2 on 2026-03-19 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='memo',
            name='memo_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('FINANCE', 'Finance'), ('HR', 'Human Resources'), ('IT', 'Information Technology'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='memo',
            name='reference_number',
            field=models.CharField(db_index=True, editable=False, max_length=100, unique=True),
        ),
    ]
