# Generated by Django 6.0.2 on 2026-02-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='fields_schema',
            field=models.JSONField(default=list, help_text='JSON list of field definitions for this template'),
        ),
    ]
