# Generated by Django 6.0.2 on 2026-02-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0007_documenttype_fields_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='template_file',
            field=models.CharField(blank=True, help_text='Path to the template file (e.g. backendapp/custom_templates/my_template.html)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='template_html',
            field=models.TextField(blank=True, help_text='HTML template for the document type', null=True),
        ),
    ]
