# Generated by Django 6.0.2 on 2026-02-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0008_documenttype_template_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='ui_config',
            field=models.JSONField(blank=True, default=dict, help_text='Puck UI configuration for the template builder', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked')], default='valid', help_text='Status of the document (valid/revoked)', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can create documents.'),
        ),
    ]
