# Generated by Django 6.0.2 on 2026-02-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0010_add_verification_attempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationAttempt',
        ),
    ]
