# Generated by Django 6.0.3 on 2026-03-21 11:27

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('autho', '0001_initial'),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=10)),
                ('idx', models.CharField(db_index=True, editable=False, max_length=20, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=True, help_text='Designates whether the user can create documents.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='autho.merchant')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='permission.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'documentapp_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable label, e.g. 'Main Logo'", max_length=100)),
                ('file', models.ImageField(help_text='The uploaded image file', upload_to='assets/')),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('signature', 'Signature'), ('stamp', 'Stamp')], default='logo', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Mark as the default asset for its type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documentapp_companyasset',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the document type (e.g., certificate, receipt)', max_length=50, unique=True)),
                ('template_html', models.TextField(blank=True, help_text='HTML template for the document type', null=True)),
                ('template_file', models.CharField(blank=True, help_text='Path to the template file (e.g. documentapp/custom_templates/my_template.html)', max_length=255, null=True)),
                ('fields_schema', models.JSONField(default=list, help_text='JSON list of field definitions for this template')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template. Null means global system template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documentapp_template',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_field', models.CharField(db_index=True, help_text='Unique verification code', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^[A-Z0-9]+$')])),
                ('metadata', models.JSONField(help_text='Flexible object for document data')),
                ('pdf_url', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked')], default='valid', help_text='Status of the document (valid/revoked)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documentapp.template')),
            ],
            options={
                'db_table': 'documentapp_document',
            },
        ),
    ]
