# Generated by Django 6.0.2 on 2026-02-12 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_document_html_content_alter_document_tracking_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tracking_field',
            field=models.CharField(db_index=True, help_text='Unique verification code', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^[A-Z0-9]+$')]),
        ),
    ]
