# Generated by Django 6.0.2 on 2026-02-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_user_username_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the document type (e.g., certificate, receipt)', max_length=50, unique=True)),
                ('template_html', models.TextField(help_text='HTML template for the document type')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='document',
            name='template_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=10),
        ),
    ]
