# Generated by Django 6.0.2 on 2026-02-22 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0011_delete_verificationattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this template. Null means global system template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
