# Generated by Django 6.0.2 on 2026-02-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0012_documenttype_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='ui_config',
        ),
    ]
