# Generated by Django 6.0.2 on 2026-02-25 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0013_remove_documenttype_ui_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable label, e.g. 'Main Logo'", max_length=100)),
                ('file', models.ImageField(help_text='The uploaded image file', upload_to='assets/')),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('signature', 'Signature'), ('stamp', 'Stamp')], default='logo', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Mark as the default asset for its type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
