# Generated by Django 6.0.2 on 2026-03-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0014_companyasset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentType',
            new_name='Template',
        ),
    ]
