# Generated by Django 6.0.2 on 2026-03-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0016_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_file',
            field=models.CharField(blank=True, help_text='Path to the template file (e.g. backendapp/custom_templates/my_template.html)', max_length=255, null=True),
        ),
    ]
