# Generated by Django 6.0.2 on 2026-03-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0018_alter_template_template_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='companyasset',
            table='documentapp_companyasset',
        ),
        migrations.AlterModelTable(
            name='document',
            table='documentapp_document',
        ),
        migrations.AlterModelTable(
            name='template',
            table='documentapp_template',
        ),
        migrations.AlterModelTable(
            name='user',
            table='documentapp_user',
        ),
    ]
