# Generated by Django 6.0.2 on 2026-03-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0020_user_display_name_user_merchant_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idx',
            field=models.CharField(db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
