# Generated by Django 6.0.2 on 2026-03-18 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autho', '0001_initial'),
        ('permission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('is_obsolete', models.BooleanField(default=False, help_text='Soft delete flag. True means the record is obsolete and should not be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('conditions', models.JSONField(default=dict)),
                ('ttl', models.PositiveIntegerField(blank=True, help_text='Expires in seconds', null=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_chains', to='autho.merchant')),
            ],
            options={
                'verbose_name': 'Approval Chain',
                'verbose_name_plural': 'Approval Chains',
            },
        ),
        migrations.CreateModel(
            name='ApprovalChainAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('is_obsolete', models.BooleanField(default=False, help_text='Soft delete flag. True means the record is obsolete and should not be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('ttl', models.PositiveIntegerField(blank=True, help_text='Expires in seconds', null=True)),
                ('is_first', models.BooleanField(default=False)),
                ('allowed_actors', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='+', to='permission.role')),
                ('approval_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='approvals.approvalchain')),
                ('next_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prev_actions', to='approvals.approvalchainaction')),
            ],
            options={
                'verbose_name': 'Approval Chain Action',
                'verbose_name_plural': 'Approval Chain Actions',
            },
        ),
        migrations.CreateModel(
            name='ApprovalChainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('is_obsolete', models.BooleanField(default=False, help_text='Soft delete flag. True means the record is obsolete and should not be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_label', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('obj_idx', models.CharField(db_index=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_chain_logs', to=settings.AUTH_USER_MODEL)),
                ('approval_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='approvals.approvalchainaction')),
                ('approval_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='approvals.approvalchain')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_chain_logs', to='autho.merchant')),
                ('next_approval_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_logs', to='approvals.approvalchainaction')),
                ('previous_log_in_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_logs_in_chain', to='approvals.approvalchainlog')),
            ],
            options={
                'verbose_name': 'Approval Chain Log',
                'verbose_name_plural': 'Approval Chain Logs',
            },
        ),
    ]
